// All values are fractions of avatar size (0–1) unless noted
export const EXPRESSIONS = {
  neutral: {
    eyeScaleY: 1,
    eyeOffsetY: 0,
    pupilScale: 1,
    blushOpacity: 0,
    browLeftTilt: -2,
    browRightTilt: 2,
    browOffsetY: 0,
    mouthCurve: 2,      // positive = smile, negative = frown (px relative to center)
    mouthWidth: 0.28,
    sparkle: false,
    questionMark: false,
  },
  happy: {
    eyeScaleY: 0.7,
    eyeOffsetY: 1,
    pupilScale: 1.1,
    blushOpacity: 0.5,
    browLeftTilt: -1,
    browRightTilt: 1,
    browOffsetY: -1,
    mouthCurve: 9,
    mouthWidth: 0.32,
    sparkle: false,
    questionMark: false,
  },
  excited: {
    eyeScaleY: 0.6,
    eyeOffsetY: 2,
    pupilScale: 1.3,
    blushOpacity: 0.85,
    browLeftTilt: -3,
    browRightTilt: 3,
    browOffsetY: -3,
    mouthCurve: 13,
    mouthWidth: 0.36,
    sparkle: true,
    questionMark: false,
  },
  sad: {
    eyeScaleY: 1,
    eyeOffsetY: 0,
    pupilScale: 0.85,
    blushOpacity: 0,
    browLeftTilt: 2,
    browRightTilt: -2,
    browOffsetY: 2,
    mouthCurve: -7,
    mouthWidth: 0.26,
    sparkle: false,
    questionMark: false,
  },
  angry: {
    eyeScaleY: 0.85,
    eyeOffsetY: 0,
    pupilScale: 0.9,
    blushOpacity: 0,
    browLeftTilt: 4,
    browRightTilt: -4,
    browOffsetY: -2,
    mouthCurve: -4,
    mouthWidth: 0.25,
    sparkle: false,
    questionMark: false,
  },
  fear: {
    eyeScaleY: 1.2,
    eyeOffsetY: -1,
    pupilScale: 1.2,
    blushOpacity: 0,
    browLeftTilt: 0,
    browRightTilt: 0,
    browOffsetY: 2,
    mouthCurve: -2,
    mouthWidth: 0.22,
    sparkle: false,
    questionMark: false,
  },
  confused: {
    eyeScaleY: 1,
    eyeOffsetY: 0,
    pupilScale: 0.95,
    blushOpacity: 0,
    browLeftTilt: 3,
    browRightTilt: -1,
    browOffsetY: 0,
    mouthCurve: 2,
    mouthWidth: 0.22,
    sparkle: false,
    questionMark: true,
  },
}

export const VALID_EMOTIONS = Object.keys(EXPRESSIONS)
